### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by DarkLotus** [MythikGN/Mythik#1]
Need to build out a list of what needs to work.

Alpha - Phase 1

- [x] Client 2.0.3 support allowing access to all features, including new gumps, and item names.
- [x] Client 2.0.3 - 5.0.9 Support for LBR/AOS Models and support for LBR/AOS/SE/ML items and equipment.
- [x] Movement adjusted to reflect spheres less stringent checks.
- [ ]  Magery Spells, basic behaviour consistent with sphere, timings and dmg excluded.
- [ ] Reduce Bugs to the point where testers spend longer playing than writing bug reports.

Beta - Phase 2

- [ ] First pass balancing Magery / Melle in Pvp, ie tuning timings / swing speeds
- [ ] All skills usable and functional as expected
- [ ] All Santiago custom crafted content
- [ ] First pass balance new player experience ( ie can a new player kill a skeleton )
- [ ] Basic balancing of drop rates / gold etc
- [ ] Basic balancing of npc pricing
- [ ] Skill gain rates 
- [ ] Release to public beta testing

Pre-Release Phase 3
- [ ] Balance and Fixes based on player feedback

Release
- [ ] Continue balance fixes

Post Release
- [ ] Content patch one, Opening of Ilsh - new mobiles, mounts
- [ ] Content patch two, Opening of Doom, new mobiles and equipment
